// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:24c40839-47bf-46f4-ba87-1ac9091ad671",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IOAadKb3j",
    "aws_user_pools_web_client_id": "7tv3998ns1hcliqi6d8qg2kn4s"
};


export default awsmobile;
